config/routes.rb
Impchimp::Application.routes.draw do

  root 'static_pages#index'
  resources :pizzas 

end

app/models/pizza.rb
class Pizza < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController

	def index 
		@pizzas = Pizza.all
	end 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index 

	end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Impchimp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "Austrailian Pizza", root_path, :class=>'brand' %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
      </div>
 
    </div>
  </div>
</div>

<%= yield %>

</body>
</html>

app/views/pizzas/index.html.erb
<% @pizzas.each do |pizza| %>
	<div class="stolen-frosty span6 offset3 text-center">
		<h1 class="stolen-h1">
			<%= pizza.name %>
		</h1>
		<h2>
			Lat: <%= pizza.lat %>
		</h2>
		<h2>
			Lng: <%= pizza.lng %>
		</h2>


		<%= image_tag "http://maps.googleapis.com/maps/api/staticmap?zoom=13&size=600x300&maptype=roadmap
&markers=color:blue%7Clabel:#{pizza.name}%7C#{pizza.lat},#{pizza.lng}&sensor=false" %>

		<br/>
	</div>	

<% end %>

app/views/static_pages/index.html.erb
<div class="stolen-frosty span6 offset3 text-center"> 
	<h1>Gimme Pizza!</h1>

	<%= link_to 'Pizza', pizzas_path, :class => 'btn btn-info btn-large' %>
</div>